### ISSUE TITLE
`art` presets

### ISSUE THREAD

**Issue by michaeltlombardi** [platenio/platen#23]
In addition to defining all of the properties for adding art in-line and the built-in defaults, we should support users defining presets for art for convenience.

We should recognize two types of presets: styles and artworks.

## Style Presets

Style presets should be a shorthand way for customizing the styling of artwork and pull the render-hook defined defaults into a `_default` entry in the `platen.art.styles._default` data.

```yaml
figure:
  classes:
    - platen-art
image:
  classes: []
caption:
  classes: []
content_warning:
  figure:
    classes:
      - platen-content-warning
  input:
    type: checkbox
    classes:
      - platen-content-warning
    name_prefix: toggle-content-warning
    id_prefix: content-warning
  label:
    content_prefix: "Content Warning:"
```

To use a defined style other than default:

```markdown
<!-- uses style from data/platen/art/styles/winter_wanderers/example.yaml -->
![art:Boreal Arachnid](/images/boreal_arachnid)
{
  style="winter_wanderers.example"
}
```

## Artwork Presets

For entries in the `platen.art.works` site data, users should be able to define art that they can then reference in their Markdown with the `work` attribute, like so:

```yaml
# platen.art.works.boreal_arachnid.yaml
Name: Boreal Arachnid
# Uses the default style unless specified.
# Can inline a valid style definition or
# use dot notation to reference a style.
# Style: _default 
# Style: winter_wanderers.example
src: /images/cover.png
alt: A rainbow-colored spider rearing back, launching spines from its forelegs
class: half
content_warning: Spiders
caption: The _Boreal Arachnid_ attacks
```

```markdown
![art:](work:boreal_arachnid)
```

```markdown
![art:]()
{
  work="BorealArachnid"
}
```

In all cases, authors can override the preset's behavior by specifying additional attributes.

Setting overrides should follow this pattern:

1. Default style preset
1. Specific style preset
1. Work preset
1. Attributes
