### ISSUE TITLE
`itchio` presets

### ISSUE THREAD

**Issue by michaeltlombardi** [platenio/platen#25]
In addition to defining all of the properties for embedding an itchio widget in-line and the built-in defaults, we should support users defining presets for convenience.

For entries in the `Platen.Embeds.Itch` site data, users should be able to define embeds they can then reference in their Markdown with the `preset` parameter, like so:

```yaml
# Isle.yaml
id: 1765719
title: The Isle by Luke Gearing
linkback: true
square: true
```
```yaml
# UNCONQUERED.yaml
id: 12345
title: UNCONQUERED by Monkey's Paw Games
backgroundColor: "#d3d3ac"
borderColor: "#FA5059"
borderWidth: 3
buttonColor: "#E53B44"
linkback: true
textcolor: "#000000"
```

``````markdown
## Shortcode Syntax

{{< itch preset="Isle" >}}

{{< itch preset="UNCONQUERED" square=true >}}

## Codefence Syntax

```itchio
preset: Isle
```

```itchio
preset: UNCONQUERED
square: true
```
``````

## Definition Syntax

```yaml
# ShortName.yaml
id: 12345
title: Accessibility title
backgroundColor: rgb
borderColor: rgb
borderWidth: 1
buttonColor: rgb
dark: false
linkback: false
square: false
textcolor: rgb
```

## Usage Details

When an author uses a preset, the implementation should check for that preset definition and load that as the defaults. If the author specifies any other parameters, those should override the preset.
