### ISSUE TITLE
Implement CSS Injection

### ISSUE THREAD

**Issue by michaeltlombardi** [platenio/platen#41]
As a site author, I want to be able to add an arbitrary class to my pages from frontmatter and/or site configuration.

This should support overwriting and merging.

Given this config and page front matters:

```yaml
# config.yaml
params:
  platen:
    display:
      section_classes:
        - glob: /factions
          class: factions
        - glob: /factions/coasts
          class: coasts
```

```yaml
# content/f66/_index.md
cascade:
  platen_section_class: f66
```

```yaml
# content/f66/secret
platen_section_class: null
```

```yaml
# content/f66/floppypunk/daemons.md
platen_page_class: glitch
```

- every page in `content/factions` would get the `factions` class injected
- pages in `content/factions/coasts` would also get `coasts` injected, meaning the class attribute would be `class="flagrant coasts"`
- pages in `content/f66` would get the `f66` class. 
  - `content/f66/secret.md` removes the class injection
  - `content/f66/floppypunk/daemons.md` appends it's own value to the class list without removing or replacing the one from the section, making the attribute `class="f66 glitch"`

The config setting makes it possible to define globs for combining patterns. It might also be worth implementing the config setting to apply based on frontmatter keys, like tags or categories.
